fix minor bugs

diff --git a/piplnlibs.sh.in b/piplnlibs.sh.in
--- a/piplnlibs.sh.in
+++ b/piplnlibs.sh.in
@@ -54,7 +54,6 @@
 exit_status=0
 opt_silent=false
 opt_remove=false
-opt_add=false
 add_libdir=
 program_name=`basename $0`
 
@@ -65,45 +64,43 @@ glibc_default_libdir=/lib64
 
 usage()
 {
-	echo >&2 "Usage: $program_name [-rs]"
+	echo >&2 "Usage: ${program_name} [-rs]"
 	exit 2
 }
 
 for option
 do
-	case $option in
-	-*)	case $option in -*r*) opt_remove=true;; esac
-		case $option in -*s*) opt_silent=true;; esac
-		case $option in -a)
-			opt_add=true
-			shift
-			add_dir=$option
+	case ${option} in
+	-*)	case ${option} in -*r*) opt_remove=true;; esac
+		case ${option} in -*s*) opt_silent=true;; esac
+		case ${option} in -a)
+			shift;
+			add_libdir=${option};;
 		esac
-		case $option in -*[!rs]*)
-			echo "$program_name: error: invalid option $option" >&2
+		case ${option} in -*[!rs]*)
+			echo "${program_name}: error: invalid option ${option}" >&2
 			usage;;
 		esac;;
-	*)	glibc_libdir=$option;;
 	esac
 done
 
-if [ ! -d $glibc_libdir ] || [ ! -f $glibc_libdir/libc.so ]; then
-    echo "$glibc_libdir does not seem to be Glibc libdir" >&2
+if ! [ -d ${glibc_libdir} -a -f ${glibc_libdir}/libc.so ]; then
+    echo "${glibc_libdir} does not seem to be Glibc libdir" >&2
     exit 1
 fi
 
-if [ x"$glibc_libdir" == x"$glibc_default_libdir" ]; then
-	echo "$program_name: warning:" \
-	     "nothing to do, because glibc_libdir = ${glibc_default_libdir}" >&2
-	exit $exit_status
+if [ x"${glibc_libdir}" == x"${glibc_default_libdir}" ]; then
+	echo "${program_name}: warning:" \
+	     "nothing to do, because ${glibc_libdir} == ${glibc_default_libdir}" >&2
+	exit 0
 fi
 
-if $opt_remove; then
+if ${opt_remove}; then
 	find ${glibc_libdir} -maxdepth 1 -type l -name 'lib*.so*' |
 	while read lib
 	do
-		if readlink $lib | grep '^/' >/dev/null; then
-			$opt_silent || echo \
+		if readlink ${lib} | grep '^/' >/dev/null; then
+			${opt_silent} || echo \
 			   rm ${lib}
 			if rm ${lib}
 			then
@@ -115,14 +112,14 @@ if $opt_remove; then
 	done
 fi
 
-if $opt_add; then
+if [ x"${add_libdir}" != x ]; then
 	ls ${add_libdir} | grep '^lib.*\.so\(\.[0-9a-z]*\)*$' |
 	while read lib
 	do
 		if [ -f ${glibc_libdir}/$lib ]; then
 			continue
 		fi
-		$opt_silent || echo \
+		${opt_silent} || echo \
 		   ln -s ${libdir}/${lib} ${glibc_libdir}/
 		if ln -s ${libdir}/${lib} ${glibc_libdir}/
 		then
@@ -145,10 +142,10 @@ do
 	ls ${libdir} | grep '^lib.*\.so\(\.[0-9a-z]*\)*$' |
 	while read lib
 	do
-		if [ -f ${glibc_libdir}/$lib ]; then
+		if [ -f ${glibc_libdir}/${lib} ]; then
 			continue
 		fi
-		$opt_silent || echo \
+		${opt_silent} || echo \
 		   ln -s ${libdir}/${lib} ${glibc_libdir}/
 		if ln -s ${libdir}/${lib} ${glibc_libdir}/
 		then
@@ -159,8 +156,8 @@ do
 	done
 done
 
-if [ $exit_status == 0 ]; then
-    echo "$program_name succeeded"
+if [ ${exit_status} == 0 ]; then
+    echo "${program_name} succeeded"
 fi
 
-exit $exit_status
+exit ${exit_status}
