Fix -a bug

diff --git a/piplnlibs.sh.in b/piplnlibs.sh.in
--- a/piplnlibs.sh.in
+++ b/piplnlibs.sh.in
@@ -57,7 +57,6 @@ exit_status=0
 opt_silent=false
 opt_remove_only=false
 opt_remove=false
-opt_add=false
 add_libdir=
 program_name=`basename $0`
 
@@ -68,48 +67,65 @@ glibc_default_libdir=/lib64
 
 usage()
 {
-	echo >&2 "Usage: $program_name [-Rrs] [-a DIR]"
+	echo >&2 "Usage: ${program_name} [-Rrs] [DIR]"
 	exit 2
 }
 
 for option
 do
-	case $option in
-	-*)	case $option in -*R*) opt_remove_only=true
-				      opt_remove=true;;
+	case ${option} in
+	    -*)	case ${option} in -*R*) opt_remove_only=true
+					opt_remove=true;;
 		esac
-		case $option in -*r*) opt_remove=true;; esac
-		case $option in -*s*) opt_silent=true;; esac
-		case $option in -a)
-			opt_add=true
-			shift
-			add_dir=$option
+		case ${option} in -*r*) opt_remove=true;; esac
+		case ${option} in -*s*) opt_silent=true;; esac
+		case ${option} in -a)
+			shift;
+			add_libdir=${option};;
 		esac
-		case $option in -*[!Rrs]*)
-			echo "$program_name: error: invalid option $option" >&2
+		case ${option} in -*[!Rrsa]*)
+			echo "${program_name}: error: invalid option ${option}" >&2
 			usage;;
 		esac;;
-	*)	glibc_libdir=$option;;
 	esac
 done
 
-if [ ! -d $glibc_libdir ] || [ ! -f $glibc_libdir/libc.so ]; then
-    echo "$glibc_libdir does not seem to be Glibc libdir" >&2
+if ! [ -d ${glibc_libdir} -a -f ${glibc_libdir}/libc.so ]; then
+    echo "${glibc_libdir} does not seem to be Glibc libdir" >&2
     exit 1
 fi
 
-if [ x"$glibc_libdir" == x"$glibc_default_libdir" ]; then
-	echo "$program_name: warning:" \
-	     "nothing to do, because glibc_libdir = ${glibc_default_libdir}" >&2
-	exit $exit_status
+if [ x"${glibc_libdir}" == x"${glibc_default_libdir}" ]; then
+	echo "${program_name}: warning:" \
+	     "nothing to do, because ${glibc_libdir} == ${glibc_default_libdir}" >&2
+	exit 0
 fi
 
-if $opt_remove; then
+if [ x"${add_libdir}" != x ]; then
+	ls ${add_libdir} | grep '^lib.*\.so\(\.[0-9a-z]*\)*$' |
+	while read lib
+	do
+		if [ -f ${glibc_libdir}/$lib ]; then
+			continue
+		fi
+		${opt_silent} || echo \
+		   ln -s ${libdir}/${lib} ${glibc_libdir}/
+		if ln -s ${libdir}/${lib} ${glibc_libdir}/
+		then
+			:
+		else
+			exit_status=1
+		fi
+	done
+	exit 0
+fi
+
+if ${opt_remove}; then
 	find ${glibc_libdir} -maxdepth 1 -type l -name 'lib*.so*' |
 	while read lib
 	do
-		if readlink $lib | grep '^/' >/dev/null; then
-			$opt_silent || echo \
+		if readlink ${lib} | grep '^/' >/dev/null; then
+			${opt_silent} || echo \
 			   rm ${lib}
 			if rm ${lib}
 			then
@@ -123,24 +139,6 @@ fi
 
 $opt_remove_only && exit $exit_status
 
-if $opt_add; then
-	ls ${add_libdir} | grep '^lib.*\.so\(\.[0-9a-z]*\)*$' |
-	while read lib
-	do
-		if [ -f ${glibc_libdir}/$lib ]; then
-			continue
-		fi
-		$opt_silent || echo \
-		   ln -s ${libdir}/${lib} ${glibc_libdir}/
-		if ln -s ${libdir}/${lib} ${glibc_libdir}/
-		then
-			:
-		else
-			exit_status=1
-		fi
-	done
-fi
-
 if [ -n "${PIP_LIBRARY_PATH:-$LD_LIBRARY_PATH}" ]; then
 	extra_libdirs=`echo "${PIP_LIBRARY_PATH:-$LD_LIBRARY_PATH}" |
 		tr ':' '\012' | grep '^/'`
@@ -153,10 +151,10 @@ do
 	ls ${libdir} | grep '^lib.*\.so\(\.[0-9a-z]*\)*$' |
 	while read lib
 	do
-		if [ -f ${glibc_libdir}/$lib ]; then
+		if [ -f ${glibc_libdir}/${lib} ]; then
 			continue
 		fi
-		$opt_silent || echo \
+		${opt_silent} || echo \
 		   ln -s ${libdir}/${lib} ${glibc_libdir}/
 		if ln -s ${libdir}/${lib} ${glibc_libdir}/
 		then
@@ -167,8 +165,8 @@ do
 	done
 done
 
-if [ $exit_status == 0 ]; then
-    echo "$program_name succeeded"
+if [ ${exit_status} == 0 ]; then
+    echo "${program_name} succeeded"
 fi
 
-exit $exit_status
+exit ${exit_status}
